---
title: "Differntial_expression"
author: "Caden McQuillen"
date: '2023-04-14'
output:
  html_document:
    toc: yes
---

## Load DEseq object
```{r}

library(DESeq2)
library(magrittr)

#load DEseq object
load("/Users/Caden/Desktop/angsd/project/angsd_project/DEseq/NPC_DEseq.RData")
DESeq.ds
```

## DE Analysis

### Run DE
```{r}
DESeq.ds %<>% DESeq()
```

### Check raw p value distrubtion 
```{r}
rowData(DESeq.ds)$WaldPvalue_condition_GPE_vs_Control %>%
hist(breaks=19, main="Raw p-values for GPE vs Control")
```
### Check logFC of significant genes
```{r}
DGE.results <- results(DESeq.ds, independentFiltering = TRUE, alpha = 0.05)
head(DGE.results)
summary(DGE.results)
table(DGE.results$padj < 0.05)

```

### Check adjusted p value distrubtiuon
```{r}
DGE.results$padj %>%
hist(breaks=19, main="Adjusted p-values for GPE vs Control")
```

### Sort DEGs
```{r}
DGE.results.sorted <- DGE.results %>% `[`(order(.$padj),)
head(DGE.results.sorted)
```

## Heatmap
```{r}
library(pheatmap)
# identify genes with the desired adjusted p-value cut-off
DGEgenes <- rownames(subset(DGE.results.sorted, padj < 0.05))
rlog.dge <- DESeq.rlog[DGEgenes,] %>% assay
pheatmap(rlog.dge, scale="row",
show_rownames=FALSE, main="DGE (row-based z-score)")
```

## Volcano Plot
```{r, fig.height=8}
library(EnhancedVolcano)
vp1 <- EnhancedVolcano(DGE.results,
lab=rownames(DGE.results),
x='log2FoldChange', y='padj',
pCutoff=0.05,
title="GPE / Control")
print(vp1)
```

## Add gene names
```{r}

#Trim ensembl ids
ensembl_ids <-rownames(DGE.results)
fixed_names <- sapply(strsplit(ensembl_ids, ".", fixed=T), function(x) x[1])
ensembl_ids_df <- data.frame(ensembl_ids, fixed_names)



library(org.Hs.eg.db)
human <- org.Hs.eg.db
## examine what keytypes are available to query the database
keytypes(human)

annot.DGE <- select(human, keys=ensembl_ids_df$fixed_names,
keytype="ENSEMBL" , columns="SYMBOL")
colnames(annot.DGE) <- c("fixed_names", "SYMBOL")

ensembl_ids_df <- merge(x=ensembl_ids_df,y=annot.DGE, 
        by="fixed_names", all.x=TRUE)

DGE.results.sorted$ensembl_ids <- rownames(DGE.results.sorted)
DGE.results.sorted <- as.data.frame(DGE.results.sorted)
DGE.results.sorted <- merge(x = DGE.results.sorted, y = ensembl_ids_df, by= "ensembl_ids", all.x=TRUE)
DGE.results.sorted <- DGE.results.sorted[,-8]

```
## Pathway enrichment
```{r}
library(enrichR)
websiteLive <- getOption("enrichR.live")
if (websiteLive) {
    listEnrichrSites()
    setEnrichrSite("Enrichr") # Human genes   
}
dbs <- listEnrichrDbs()

sig_DEGs <- subset(DGE.results.sorted, padj < 0.05)
sig_upRegulated_DEGs <- subset(sig_DEGs, log2FoldChange > 0)
sig_downRegulated_DEGs <- subset(sig_DEGs, log2FoldChange < 0)

upReg_pathways <- enrichr(as.vector(na.omit(sig_upRegulated_DEGs$SYMBOL)), "KEGG_2021_Human")
upReg_pathways[["KEGG_2021_Human"]]

downReg_pathways <- enrichr(as.vector(na.omit(sig_downRegulated_DEGs$SYMBOL)), "KEGG_2021_Human")
downReg_pathways[["KEGG_2021_Human"]]

plotEnrich(upReg_pathways[[1]], showTerms = 15, numChar = 40, y = "Count", orderBy = "Adjusted.P.value")
plotEnrich(downReg_pathways[[1]], showTerms = 15, numChar = 40, y = "Count", orderBy = "Adjusted.P.value")
```

